### ISSUE TITLE
online_delete does not work, disk usage expands

### ISSUE THREAD

**Issue by skinderis** [XRPLF/rippled#3182] opened 2019-12-10 09:30 UTC
Hi, I have a problem. Running rippled('build_version': '1.3.1') on docker container (ubuntu 18.04 OS) with `online_delete` set to `256` and `ledger_history` set to `150000`, but disk gets loaded until reaches full disk space.

configs of node_db, node_size and ledger_history are set:
```
[node_db]
type=NuDB
path=/home/coin/data/
online_delete 256
advisory_delete 0

[node_size]
medium

[ledger_history]
150000
```

Before disk usage reached 300 GB (with `ledger_history=300000` and `online_delete=150000`), so I resized the volume to 500 GB, reduced `online_delete` to `256`, `ledger_history` to `150000`. But, I am noticing that disk usage already reached 150 GB and keeps growing (so the online deletion function is not initiated).

Maybe there is a good working example of rippled config file to not expand lets say 300 GB disk usage?
Could anyone help me with this problem? Thanks!

**Comment by nbougalis** [comment] 2019-12-11 20:07
I believe the issue is that the config snippet you provide above is malformed. You have:
```
online_delete 256
advisory_delete 0
```

There are equal signs missing between the key and the value; the above should read:
```
online_delete=256
advisory_delete=0
```

Please make the change and restart your server. If this solves your problem, please close this issue. We'll close it for you if we don't hear back within a week.

**Comment by skinderis** [comment] 2019-12-12 13:41
@nbougalis, thanks for advice. I ran with these settings now:

```
[node_db]
type=NuDB
path=/home/coin/data/
online_delete=256
advisory_delete=0

[ledger_history]
256
```

let's if it won't expand and if online deletion works, should take few GBs I guess.

**Comment by skinderis** [comment] 2019-12-12 16:05
I have noticed my container runs 2 processes of rippled 
![image](https://user-images.githubusercontent.com/24273695/70728249-beba1a00-1d09-11ea-8136-e07ef678d25f.png)
and creates several rippledb.XXXX files. Is it fine or I run too many instances at the same time?

**Comment by nbougalis** [comment] 2019-12-16 07:14
##### Re: two instances: :heavy_check_mark: 
The two instances are by design; one is the main `rippled` instance and the other is a "watcher" process, which monitors the primary instance and restarts it in case of failure. So that's correct! 

##### Re: several `rippledb.XXXX` files: :heavy_check_mark: 
That is correct; when utilizing online delete, you will see two sets of databases, which the server users to perform the rotation. Based on the presence of two sets of databases, your server is configured with online deletion enabled.

**Comment by intelliot** [comment] 2023-03-02 21:33
Closing due to inactivity. If the issue persists, please open a new issue.

**Closed by intelliot** 2023-03-02 21:33 UTC
