### ISSUE TITLE
fixReducedOffersV1 still not covering all cases and book blocking (Version: 2.1.0)

### ISSUE THREAD

**Issue by shortthefomo** [XRPLF/rippled#4937] opened 2024-02-29 19:20 UTC
## Issue Description
Amendment fixReducedOffersV1 https://xrpl.org/resources/known-amendments#fixreducedoffersv1 is still not fixing all case where the order book is blocked 

two cases have now been identified on mainnet.

## Supporting Files
![GHhUFv5XYAAVWtV](https://github.com/XRPLF/rippled/assets/508629/8c1daa43-1b20-4f8e-a498-9e5f0afb27d9)
![GHYCDJ_X0AAEvjm](https://github.com/XRPLF/rippled/assets/508629/2f6df5fa-b0f1-4086-870d-60bfc2f3c8eb)

**Comment by scottschurr** [comment] 2024-03-01 01:51
@lathanbritz, I'm disappointed but not surprised that I didn't fix all the ways that order books can be blocked.  I have something else I'm working on right now, but this issue is next on my list after that's done.

It would help a lot if you can identify a specific historic transaction that failed because of this blockage.  Of course you can only point at transactions that fail with a `tec` code.  So there may not be any such transactions on the network.  But being able to replay such a transaction might help me see the reason behind the blockage.  If you know of a transaction like that please mention it here.  Thanks.

**Comment by lathanbritz** [comment] 2024-03-01 20:35
@scottschurr rLtdxMMXPs21PYnnSiwm85EabdHDH4oVhi has blocked the USD book (its the one with the partially filled order), it does not have too  many tx 

<img width="620" alt="Screenshot 2024-03-01 at 17 33 02" src="https://github.com/XRPLF/rippled/assets/508629/7dc0a8f1-dfe8-4964-8cde-74e34f853748">

**Comment by scottschurr** [comment] 2024-03-01 21:23
@lathanbritz that helps, thanks.  That's current?  Like that's the state of the book for, say, ledger 86325875?  Is there a way you can get the ledger index of the blocking offer (from rLtdxMMXPs21PYnnSiwm85EabdHDH4oVhi).  That would be a big help.  Then I can look back at that offer's history.

**Comment by lathanbritz** [comment] 2024-03-25 15:56
@scottschurr we have another instance today


ledger index 86,858,489 its present
account https://xrpscan.com/account/rJTyFN9PYy9uWJ3ixsSBfvhZGgvvjNt8MV

**Comment by scottschurr** [comment] 2024-03-26 16:32
@lathanbritz, thanks for the information on that recent blockage.

I have a unit test that is able to reproduce the last blockage that you reported (by `rLtdxMMXPs21PYnnSiwm85EabdHDH4oVhi`).  I'm currently looking into how to prevent the source of that particular blockage.

When I get an opening I'll research this more recent blockage, since it may not have the same source as the older one that I'm currently looking at.

**Comment by scottschurr** [comment] 2024-04-10 22:29
@shortthefomo, first the good news: I found the source of the problem for the USD/Bitstamp:XRP blockage that you reported earlier.  I have a proposed fix (not yet a pull request), but that will of course need to go through code review.

Regarding the reported order book blockage in ledger 86,858,489 I have less good news.  I analyzed the top-most 150 offers in the...

    "TakerGets": "CSC"/"rCSCManTZ8ME9EoLrSHHYKW8PPwWMgkwr",
    "TakerPays": "XRP"

order book in that ledger.  That included the one you identified with TakerPays: "4" (that was offer 49).  I don't see how any of those 150 offers could be blockers.  I'm not saying you didn't see something funny with that order book.  But I don't understand the nature of the symptom you were seeing.

All-in-all, however, it is forward progress to identify an additional source of order book blockage and find a fix for it.  Thanks for the help.

**Comment by shortthefomo** [comment] 2024-04-18 01:07
Great news!

The symptoms that I see that makes it simple to spot is simply taking the first offers off ASK/BID books and then checking for a negative spread. If it's negative those books (ASK and BID) had an order that is "stuck".


That's how ive been identifying them, not sure if that information helps here.
Thank you for all the effort on this @scottschurr

**Comment by intelliot** [comment] 2024-07-01 21:11
this is expected to be fixed by `fixReducedOffersV2`, introduced in [2.3.0-b1](https://github.com/XRPLF/rippled/releases/tag/2.3.0-b1)

feel free to re-open this issue if more needs to be done

**Closed by intelliot** 2024-07-01 21:11 UTC
