### ISSUE TITLE
Setting NFTokenMinter  to '' causes it to be set to 'rrrrrrrrrrrrrrrrrrrrrhoLvTp' (Version: 1.9.4)

### ISSUE THREAD

**Issue by lathanbritz** [XRPLF/rippled#4405] opened 2023-02-01 02:47 UTC
## Issue Description
was looking to set my NFTokenMinter value back to default on my account, took a guess and passed it a '' string it was then set to the account of 'rrrrrrrrrrrrrrrrrrrrrhoLvTp'

## Steps to Reproduce
set NFTokenMinter to '' on a AccountSet transaction.
<code>
{
                    TransactionType: 'AccountSet',
                    Account: process.env.PAYMENT_ADDRESS,
                    NFTokenMinter:'',
                    Fee: String(base_fee),
                    Sequence: account_info.account_data.Sequence,
                    SetFlag: 10
}
</code>

## Expected Result
It should throw a error in this case 

## Actual Result
instead it allowed the transaction through and set the NFTokenMinter to 'rrrrrrrrrrrrrrrrrrrrrhoLvTp'

## Environment
websocket to -> 'wss://s.altnet.rippletest.net:51233'

**Comment by ximinez** [comment] 2023-02-01 16:37
I don't know if this is intended behavior or not, but just to clarify, the correct way to clear the token minter flag is to clear the `asfAuthorizedNFTokenMinter` flag: `ClearFlag: 10`. For more info: https://xrpl.org/accountset.html#accountset-flags

**Comment by intelliot** [comment] 2023-02-02 23:28
For those curious, `rrrrrrrrrrrrrrrrrrrrrhoLvTp` is the base58 XRPL-address encoding of `0`. https://xrpl.org/accounts.html#special-addresses

When setting `NFTokenMinter`, I think client libraries should validate that the address is valid, and an empty string should not be permitted.

@lathanbritz can you try following @ximinez 's suggestion in order to set the `NFTokenMinter` back to default? Does that work for you?

**Comment by lathanbritz** [comment] 2023-02-02 23:31
Yes have reverted it with the actual clear flag command. So it is not that it is stuck. Simply more highlighting that the incorrect thing here should not be allowed through and be trapped.

**Comment by intelliot** [comment] 2023-02-02 23:40
1. Setting `NFTokenMinter` to `''` or `'rrrrrrrrrrrrrrrrrrrrrhoLvTp'` does not cause any harm, since that is an address that won't mint anyway. (It's a black hole address)
2. When creating the transaction, did you use the AccountSet validate method in the client library? If so, it's possible to trap the mistake there. However, users aren't required to use the helper; you can always create transactions "manually".
3. The "correct" way is documented here: https://xrpl.org/nftoken-authorized-minting.html#unassigning-an-authorized-minter

**Comment by kennyzlei** [comment] 2023-06-08 18:09
@lathanbritz do you feel this rippled issue is now resolved with the new issues we have on client libraries to prevent setting to empty string?

**Comment by lathanbritz** [comment] 2023-06-09 01:16
Yea that is great 👍🏻

**Closed** 2023-06-09 01:16 UTC
