### ISSUE TITLE
ledgerNotFound in transaction_entry after ledger_request

### ISSUE THREAD

**Issue by dselyuzhitskiy** [XRPLF/rippled#2481] opened 2018-04-16 09:10 UTC
Hi there, is it possible to get transaction entry on a ledger, that already cleaned ? 

On a local node we made /opt/ripple/bin/rippled  ledger_request 37888900 and answer is 
```json
{
   "result" : {
      "ledger" : {
         "accepted" : true,
         "account_hash" : "C0511932022DAC08AA6328A697D48AF0BFD7319F3387B05D47534EB8E49BA1C8",
         "close_flags" : 0,
         "close_time" : 576780371,
         "close_time_human" : "2018-Apr-11 16:46:11",
         "close_time_resolution" : 10,
         "closed" : true,
         "hash" : "1517BD8C139F16C723F39AF16025407AB1AB291E828E8FDE739C1C53026B644D",
         "ledger_hash" : "1517BD8C139F16C723F39AF16025407AB1AB291E828E8FDE739C1C53026B644D",
         "ledger_index" : "37888900",
         "parent_close_time" : 576780370,
         "parent_hash" : "B9675FB23D82162F32CA5C2BCA14EB3453AB2EEEFB805125C511DA8A155F7E31",
         "seqNum" : "37888900",
         "totalCoins" : "99992355360185433",
         "total_coins" : "99992355360185433",
         "transaction_hash" : "BC98AE34C3A46690BCD8EC958FA5951739573E33022C34E9FE30E0A3F114670B"
      },
      "ledger_index" : 37888900,
      "status" : "success"
   }
}
```

but after /opt/ripple/bin/rippled  transaction_entry some_transaction_hash_in_this_ledger 37888900 answer is

```json
{
   "result" : {
      "error" : "lgrNotFound",
      "error_code" : 21,
      "error_message" : "ledgerNotFound",
      "request" : {
         "command" : "transaction_entry",
         "ledger_index" : 37888900,
         "tx_hash" : some_transaction_hash_in_this_ledger
      },
      "status" : "error"
   }
}
```

**Comment by MarkusTeufelberger** [comment] 2018-04-16 14:49
See #1873

**Comment by dselyuzhitskiy** [comment] 2018-04-18 08:02
@MarkusTeufelberger thanks. Do you know any way to get transactions from missing ledger ?

**Comment by MarkusTeufelberger** [comment] 2018-04-18 10:54
As long as the ledger is still in the range that your node is configured to store(!), you can take a look at `ledger_cleaner`.

**Comment by vhendriks81** [comment] 2018-04-27 08:41
afaik you can connect to one of ripples public node which had a full history (s2.ripple.com i believe?) using the connect command and then you can request the missing ledger

**Comment by mDuo13** [comment] 2019-08-02 02:02
#2800 is a duplicate of this.

**Comment by intelliot** [comment] 2023-03-14 14:46
Closing in favor of #2800

**Closed by intelliot** 2023-03-14 14:46 UTC
Labels: Feature Request
