### ISSUE TITLE
Consider supporting deterministic builds

### ISSUE THREAD

**Issue by nbougalis** [XRPLF/rippled#3427] opened 2020-06-01 15:36 UTC
Someone should investigate the possibility of using [Gitian](https://gitian.org/) to build packages, so that the builds are reproducible. That way a third party can check out and build a given version of the code and produce a binary _identical_ to the one published.

Deterministic builds will result in enhanced confidence about released binary packages.

**Comment by MarkusTeufelberger** [comment] 2020-06-01 19:14
I did some work on building with Bazel (https://bazel.build/) a while back - upside is that there would be other benefits, downside is that the team that mainly contributes to `rippled` seems to be into cmake.

I'm not so sure if a whole VM as in gitian is needed, a deterministic build using docker might be enough already.

**Comment by intelliot** [comment] 2023-04-03 19:16
@thejohnfreeman do you have a recommendation here? If not, who would you like to have a look at this?

I'd also be fine with closing this as "will not fix" since I haven't seen a lot of demand for reproducible builds. Folks who want to be certain about what they are running can/should build from source.

**Comment by thejohnfreeman** [comment] 2023-04-03 22:21
If we don't want to switch tools, then this would involve tracking down the sources of non-determinism, typically timestamps like a "built on date", and eliminating them. I'm not familiar with the sources of non-determinism in our toolchains. Personally, I would put this at low priority. Could make for a good summer intern project with some guidance.

**Comment by intelliot** [comment] 2023-04-06 18:37
I haven't seen much demand for this, and the most reliable way for someone to know what they are getting is to build from source. I'll close this issue, but if anyone needs this, feel free to open a new issue.

**Closed by intelliot** 2023-04-06 18:37 UTC
Labels: Request for Comments, Feature Request
