### ISSUE TITLE
[Sync error] (Version: [1.10.1])

### ISSUE THREAD

**Issue by DreamHackchosenone** [XRPLF/rippled#4482] opened 2023-03-31 09:52 UTC
## Issue Description
2023-Mar-31 09:51:26.874722246 UTC Flow:FTL Old payment rules are required for this transaction. Assuming this is a replay and running with the new rules.
2023-Mar-31 09:51:26.874786534 UTC Flow:FTL Old payment rules are required for this transaction. Assuming this is a replay and running with the new rules.
2023-Mar-31 09:51:26.876252946 UTC ValidatorList:WRN New quorum of 18446744073709551615 exceeds the number of trusted validators (36)
2023-Mar-31 09:51:27.065783249 UTC Flow:FTL Old payment rules are required for this transaction. Assuming this is a replay and running with the new rules.
2023-Mar-31 09:51:27.066958122 UTC Flow:FTL Old payment rules are required for this transaction. Assuming this is a replay and running with the new rules.

## Environment
Ubuntu 20.04 
Boost 1.71.0.0ubuntu2

**Comment by seelabs** [comment] 2023-03-31 14:43
That means the "featureFlow" amendment is not active. This amendment was activated about seven years ago. Can you share more about what is the server doing when this occurs? Are you replaying a transaction? Connecting to a network? If so, which network? Can you share you conig file (with any secrets removed, of course).

**Comment by DreamHackchosenone** [comment] 2023-03-31 16:16
> That means the "featureFlow" amendment is not active. This amendment was activated about seven years ago. Can you share more about what the server doing when this occurs? Are you replaying a transaction? Connecting to a network? If so, which network? Can you share you config file (with any secrets removed, of course).

I upgraded rippled version and restart 
I connect mainet, her is my config:
```
[server]
port_rpc_admin_local
port_peer
port_ws_admin_local

[port_rpc_admin_local]
port = 5005
ip = 0.0.0.0
admin = 0.0.0.0
protocol = http

[port_peer]
port = 51235
ip = 0.0.0.0
protocol = peer

[port_ws_admin_local]
port = 6006
ip = 127.0.0.1
admin = 127.0.0.1
protocol = ws

[node_size]
medium

[node_db]
type=RocksDB
path=/data/.xrp/db/rocksdb
open_files=2000
filter_bits=12
cache_mb=256
file_size_mb=8
file_size_mult=2
online_delete=100000
advisory_delete=0

[database_path]
/data/.xrp/db

#[debug_logfile]
#/data/.xrp/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

[ips]
r.ripple.com 51235

[validators_file]
validators.txt

[rpc_startup]
{ "command": "log_level", "severity": "warning" }

[ssl_verify]
1
```

**Comment by seelabs** [comment] 2023-03-31 22:41
@DreamHackchosenone Thanks for posting your config. I don't see an issue with it. Thank you for reporting it this issue. I will try to think about how this could be happening.

**Comment by DreamHackchosenone** [comment] 2023-04-03 09:09
> @DreamHackchosenone Thanks for posting your config. I don't see an issue with it. Thank you for reporting it this issue. 
I deleted a line in validators.txt and now the log does not have this issue，and sync to the latest height
Now validators.txt configuration looks like this：
[validator_list_sites]
https://vl.ripple.com
https://vl.xrplf.org

[validator_list_keys]
#vl.ripple.com
ED2677ABFFD1B33AC6FBC3062B71F1E8397C1505E1C42C64D11AD1B28FF73F4734
# vl.xrplf.org
ED45D1840EE724BE327ABE9146503D5848EFD5F38B6D5FEDE71E80ACCE5E6E738B

**Comment by ximinez** [comment] 2023-04-03 14:40
> I deleted a line in validators.txt and now the log does not have this issue

Out of curiosity, what did you delete?

**Comment by DreamHackchosenone** [comment] 2023-04-04 01:38
> > I deleted a line in validators.txt and now the log does not have this issue
> 
> Out of curiosity, what did you delete?

It should be an out-of-date website because this configuration worked before
I can't remember the exact site

**Comment by intelliot** [comment] 2023-04-06 18:36
One possibility that comes to mind is vl.coil.com per https://github.com/XRPLF/rippled/commit/135b63dbe0a692ba6cf08987ce67a7f11962511a

@DreamHackchosenone if the problem is resolved, please close this issue.

**Closed** 2023-04-07 01:30 UTC
